theme: minima
title: The Borg Blog
author: DenBorg
email: DenBorg@TheBorgCollective.com
description: > # this means to ignore newlines until "baseurl:"
  Built with [GitHub Pages](https://pages.github.com/), this is an awesome site!
  Welcome to **The Borg Blog**!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
